import React, { useState } from 'react';
import { Shield, Sparkles, Award, CheckCircle, Mail, Phone, User, Building, Send } from 'lucide-react';

export default function Sponsorship({ onSubmitSuccess }) {
  const [selectedTier, setSelectedTier] = useState('gold');
  const [formData, setFormData] = useState({
    name: '',
    designation: '',
    company: '',
    email: '',
    phone: '',
    message: ''
  });

  const tiers = [
    {
      id: 'silver',
      name: 'Silver Seva Patron',
      amount: '₹1,50,000',
      description: 'Support critical event operations and participate as an honored community partner.',
      icon: Shield,
      color: 'text-neutral-400',
      bgColor: 'bg-neutral-50',
      borderColor: 'border-neutral-200',
      deliverables: [
        'Logo placement on website and digital event brochure',
        '2 Complimentary VIP Delegate passes',
        'Mention in post-event impact press release',
        'Corporate name on the sponsor appreciation wall'
      ]
    },
    {
      id: 'gold',
      name: 'Gold Divine Patron',
      amount: '₹3,00,000',
      description: 'Establish strong brand presence and partner with Dhara for sustainable social projects.',
      icon: Sparkles,
      color: 'text-sun-gold',
      bgColor: 'bg-[#FDFBF7]',
      borderColor: 'border-sun-gold-light',
      deliverables: [
        'Prominent logo on main backdrop and stage screens',
        '5 Complimentary VIP Delegate passes with private dining access',
        'Dedicated 1-minute audio-visual corporate profile during break',
        '1 Corporate banner stand in the exhibition/reception area',
        'Featured CSR story in the Dhara Foundations Newsletter (10k+ subscribers)'
      ]
    },
    {
      id: 'platinum',
      name: 'Platinum Maha Patron',
      amount: '₹5,00,000',
      description: 'Maximum brand integration, VIP stage representation, and co-naming of an award category.',
      icon: Award,
      color: 'text-forest-teal-light',
      bgColor: 'bg-[#eef4f1]',
      borderColor: 'border-forest-teal-light',
      deliverables: [
        'Exclusive Category Sponsor ("Divine Awards presented by [Your Logo]")',
        '10 Complimentary VIP Delegate passes with private dinner seating',
        'Opportunity to present one prestigious award on stage',
        'Full-page advertisement in the event souvenir booklet',
        'Co-branding on all press conference backdrops and promotional collaterals',
        'Collaborative CSR project video report generated by Dhara team'
      ]
    }
  ];

  const handleChange = (e) => {
    const { name, value } = e.target;
    setFormData(prev => ({ ...prev, [name]: value }));
  };

  const handleSubmit = (e) => {
    e.preventDefault();
    if (!formData.name || !formData.company || !formData.email) {
      alert('Please fill in all required fields.');
      return;
    }
    const submission = {
      module: 'Sponsorship Opportunities',
      ...formData,
      tier: tiers.find(t => t.id === selectedTier).name,
      timestamp: new Date().toISOString()
    };
    
    // Save to localstorage
    const current = JSON.parse(localStorage.getItem('dhara_submissions') || '[]');
    current.push(submission);
    localStorage.setItem('dhara_submissions', JSON.stringify(current));

    onSubmitSuccess({
      title: 'Sponsorship Proposal Received',
      message: `Pranam, ${formData.name}. Thank you for expressing interest in partnering with Dhara Foundations for the Divine Awards 2026. Your inquiry for the ${tiers.find(t => t.id === selectedTier).name} tier has been registered. Our corporate relations team will reach out to you shortly to finalize details.`,
      details: [
        { label: 'Representative', value: formData.name },
        { label: 'Organization', value: formData.company },
        { label: 'Selected Tier', value: tiers.find(t => t.id === selectedTier).name }
      ]
    });
  };

  return (
    <div className="py-12 px-4 sm:px-6 lg:px-8 max-w-6xl mx-auto">
      <div className="text-center mb-12">
        <span className="text-sun-gold font-semibold uppercase tracking-wider text-sm font-sans">Corporate Partnership</span>
        <h2 className="text-4xl font-serif text-forest-teal-dark mt-2 mb-4">Sponsorship Opportunities</h2>
        <p className="text-neutral-600 max-w-2xl mx-auto font-sans">
          Align your corporate values with divine service. Partner with Dhara Foundations to empower positive change and showcase your social commitment at the Divine Awards 2026.
        </p>
      </div>

      <div className="grid grid-cols-1 lg:grid-cols-3 gap-8 mb-16">
        {tiers.map((t) => {
          const IconComponent = t.icon;
          return (
            <div
              key={t.id}
              onClick={() => setSelectedTier(t.id)}
              className={`cursor-pointer rounded-3xl p-8 border-2 transition-all duration-300 ease-in-out flex flex-col justify-between hover:scale-102 ${
                selectedTier === t.id
                  ? 'border-sun-gold bg-white shadow-premium-hover'
                  : 'border-transparent bg-white shadow-premium'
              }`}
            >
              <div>
                <div className="flex justify-between items-center mb-6">
                  <div className={`p-3 rounded-2xl ${t.id === 'gold' ? 'bg-amber-50' : t.id === 'platinum' ? 'bg-emerald-50' : 'bg-neutral-100'}`}>
                    <IconComponent className={`w-8 h-8 ${t.color}`} />
                  </div>
                  <span className="text-2xl font-serif font-bold text-forest-teal">
                    {t.amount}
                  </span>
                </div>

                <h3 className="text-xl font-serif font-bold text-forest-teal-dark mb-3">{t.name}</h3>
                <p className="text-sm text-neutral-500 mb-6 leading-relaxed font-sans">{t.description}</p>
                
                <div className="border-t border-neutral-100 pt-6">
                  <h4 className="text-xs font-semibold uppercase tracking-wider text-neutral-400 mb-4 font-sans">Key Deliverables</h4>
                  <ul className="space-y-3">
                    {t.deliverables.map((d, index) => (
                      <li key={index} className="flex items-start text-xs font-sans text-neutral-600 leading-normal">
                        <CheckCircle className="w-4 h-4 text-sun-gold mr-2.5 shrink-0 mt-0.5" />
                        <span>{d}</span>
                      </li>
                    ))}
                  </ul>
                </div>
              </div>

              <div className="mt-8 pt-4">
                <div className={`w-full py-3 rounded-xl font-sans text-center text-sm font-semibold transition-colors duration-300 ${
                  selectedTier === t.id
                    ? 'bg-sun-gold text-forest-teal-dark shadow-md'
                    : 'bg-soft-sage text-forest-teal hover:bg-forest-teal hover:text-white'
                }`}>
                  {selectedTier === t.id ? 'Selected for Inquiry' : 'Enquire for this Tier'}
                </div>
              </div>
            </div>
          );
        })}
      </div>

      <div className="bg-[#eef4f1] rounded-3xl border border-sage-accent/50 p-8 max-w-3xl mx-auto">
        <div className="text-center mb-8">
          <h3 className="text-2xl font-serif text-forest-teal-dark">B2B Sponsorship Enquiry Form</h3>
          <p className="text-sm text-neutral-600 font-sans mt-1">Please fill in this secure form to request a formal sponsorship package and scheduling details.</p>
        </div>

        <form onSubmit={handleSubmit} className="space-y-5">
          <div className="grid grid-cols-1 md:grid-cols-2 gap-5">
            <div>
              <label className="block text-xs font-semibold uppercase tracking-wider text-forest-teal mb-2 font-sans">Contact Person *</label>
              <div className="relative">
                <User className="absolute left-3.5 top-3.5 w-4 h-4 text-neutral-400" />
                <input
                  type="text"
                  name="name"
                  required
                  placeholder="Mr. Ramesh Sharma"
                  value={formData.name}
                  onChange={handleChange}
                  className="w-full pl-10 pr-4 py-3 rounded-xl border border-neutral-200 focus:outline-none focus:ring-2 focus:ring-forest-teal focus:border-transparent transition-all duration-300 text-sm font-sans bg-white"
                />
              </div>
            </div>

            <div>
              <label className="block text-xs font-semibold uppercase tracking-wider text-forest-teal mb-2 font-sans">Designation / Role *</label>
              <div className="relative">
                <Building className="absolute left-3.5 top-3.5 w-4 h-4 text-neutral-400" />
                <input
                  type="text"
                  name="designation"
                  required
                  placeholder="Head of CSR / VP Marketing"
                  value={formData.designation}
                  onChange={handleChange}
                  className="w-full pl-10 pr-4 py-3 rounded-xl border border-neutral-200 focus:outline-none focus:ring-2 focus:ring-forest-teal focus:border-transparent transition-all duration-300 text-sm font-sans bg-white"
                />
              </div>
            </div>
          </div>

          <div className="grid grid-cols-1 md:grid-cols-2 gap-5">
            <div>
              <label className="block text-xs font-semibold uppercase tracking-wider text-forest-teal mb-2 font-sans">Company / Institution Name *</label>
              <div className="relative">
                <Building className="absolute left-3.5 top-3.5 w-4 h-4 text-neutral-400" />
                <input
                  type="text"
                  name="company"
                  required
                  placeholder="Zenith Global Corp"
                  value={formData.company}
                  onChange={handleChange}
                  className="w-full pl-10 pr-4 py-3 rounded-xl border border-neutral-200 focus:outline-none focus:ring-2 focus:ring-forest-teal focus:border-transparent transition-all duration-300 text-sm font-sans bg-white"
                />
              </div>
            </div>

            <div>
              <label className="block text-xs font-semibold uppercase tracking-wider text-forest-teal mb-2 font-sans">Preferred Sponsorship Tier</label>
              <select
                name="selectedTier"
                value={selectedTier}
                onChange={(e) => setSelectedTier(e.target.value)}
                className="w-full px-4 py-3 rounded-xl border border-neutral-200 focus:outline-none focus:ring-2 focus:ring-forest-teal focus:border-transparent transition-all duration-300 text-sm font-sans bg-white"
              >
                <option value="silver">Silver Seva Patron (₹1.5L)</option>
                <option value="gold">Gold Divine Patron (₹3.0L)</option>
                <option value="platinum">Platinum Maha Patron (₹5.0L)</option>
              </select>
            </div>
          </div>

          <div className="grid grid-cols-1 md:grid-cols-2 gap-5">
            <div>
              <label className="block text-xs font-semibold uppercase tracking-wider text-forest-teal mb-2 font-sans">Corporate Email *</label>
              <div className="relative">
                <Mail className="absolute left-3.5 top-3.5 w-4 h-4 text-neutral-400" />
                <input
                  type="email"
                  name="email"
                  required
                  placeholder="ramesh@zenith.com"
                  value={formData.email}
                  onChange={handleChange}
                  className="w-full pl-10 pr-4 py-3 rounded-xl border border-neutral-200 focus:outline-none focus:ring-2 focus:ring-forest-teal focus:border-transparent transition-all duration-300 text-sm font-sans bg-white"
                />
              </div>
            </div>

            <div>
              <label className="block text-xs font-semibold uppercase tracking-wider text-forest-teal mb-2 font-sans">Phone / Mobile *</label>
              <div className="relative">
                <Phone className="absolute left-3.5 top-3.5 w-4 h-4 text-neutral-400" />
                <input
                  type="tel"
                  name="phone"
                  required
                  placeholder="+91 98765 09876"
                  value={formData.phone}
                  onChange={handleChange}
                  className="w-full pl-10 pr-4 py-3 rounded-xl border border-neutral-200 focus:outline-none focus:ring-2 focus:ring-forest-teal focus:border-transparent transition-all duration-300 text-sm font-sans bg-white"
                />
              </div>
            </div>
          </div>

          <div>
            <label className="block text-xs font-semibold uppercase tracking-wider text-forest-teal mb-2 font-sans">Specific Branding or CSR Collaboration Goals</label>
            <textarea
              name="message"
              rows="3"
              placeholder="We are particularly interested in clean water/education projects in rural zones..."
              value={formData.message}
              onChange={handleChange}
              className="w-full px-4 py-3 rounded-xl border border-neutral-200 focus:outline-none focus:ring-2 focus:ring-forest-teal focus:border-transparent transition-all duration-300 text-sm font-sans bg-white"
            ></textarea>
          </div>

          <div className="pt-2">
            <button
              type="submit"
              className="w-full py-4 rounded-xl bg-forest-teal text-white hover:bg-forest-teal-light font-sans font-semibold text-base transition-all duration-300 ease-in-out flex items-center justify-center space-x-2 border-2 border-transparent hover:border-sun-gold cursor-pointer group"
            >
              <span>Submit Partnership Inquiry</span>
              <Send className="w-5 h-5 transition-transform duration-300 group-hover:translate-x-1" />
            </button>
          </div>
        </form>
      </div>
    </div>
  );
}
